parameters:
    app.path.gallery_images: /uploads/images/gallery
    app.path.photo_images: /uploads/images/photo
    app.path.logo_images: /uploads/images/logo

vich_uploader:
    db_driver: orm

    mappings:
       gallery_images:
           uri_prefix: '%app.path.gallery_images%'
           upload_destination: '%kernel.project_dir%/public/uploads/images/gallery'
       photo_images:
           uri_prefix: '%app.path.photo_images%'
           upload_destination: '%kernel.project_dir%/public/uploads/images/photo'
       logo_images:
           uri_prefix: '%app.path.logo_images%'
           upload_destination: '%kernel.project_dir%/public/uploads/images/logo'

